language: node_js
node_js:
 - "0.10"
 - "0.12"

before_install:
 - gem install fluentd --no-ri --no-rdoc
 - fluentd -c test/fluent.conf &

after_success: npm run-script coveralls

after_script: cat coverage/lconv.info | codeclimate

addons:
  code_climate:
    repo_token:
      secure: E8a1kV8PCPRijxWStr4wBaDie5NwEoRO3yolAW+aLVE488yWHNWfMoxtTIDx4vZ5BdsgPmpKvTOu0OUm4y3CPJsv2YJNCPsgh7gbM1VaogeNoenk9JZ6XdVXd7S6r3QTO/+SYqO7SBr/JqkiIwZDBPE71/HBwe2h7v02FM6oIn4=
